# Generated by Django 4.2.7 on 2025-09-30 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Sepatu Bola'), ('ball', 'Bola'), ('gloves', 'Sarung Tangan Kiper'), ('accessories', 'Aksesoris'), ('training', 'Peralatan Latihan'), ('fan_merch', 'Merchandise Fans'), ('equipment', 'Perlengkapan Pertandingan'), ('kids', 'Produk Anak'), ('lifestyle', 'Lifestyle & Casual Wear')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
