# Generated by Django 5.2.6 on 2025-09-15 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Sepatu Bola'), ('ball', 'Bola'), ('gloves', 'Sarung Tangan Kiper'), ('accessories', 'Aksesoris'), ('training', 'Peralatan Latihan'), ('fan_merch', 'Merchandise Fans'), ('equipment', 'Perlengkapan Pertandingan'), ('kids', 'Produk Anak'), ('lifestyle', 'Lifestyle & Casual Wear')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField()),
            ],
        ),
    ]
